name: hw01_mycard
description: "A basic Flutter app to demonstrate the usage of widgets"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
   - family: Pacifico
     fonts:
       - asset: assets/fonts/Pacifico-Regular.ttf
   - family: Source Sans Pro
     fonts:
       - asset: assets/fonts/SourceSansPro-Regular.ttf
